import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Backup & restore","description":"","frontmatter":{"title":"Backup & restore"},"headers":[],"relativePath":"admin/backup.md","filePath":"admin/backup.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "admin/backup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /admin/backup.md for this page in Markdown format</div><h1 id="backup-restore" tabindex="-1">Backup &amp; restore <a class="header-anchor" href="#backup-restore" aria-label="Permalink to &quot;Backup &amp; restore&quot;">​</a></h1><p>You can back up your camera.ui setup and restore it later, on any platform. It&#39;s in <strong>Settings → Backup</strong> (admins only).</p><h2 id="creating-a-backup" tabindex="-1">Creating a backup <a class="header-anchor" href="#creating-a-backup" aria-label="Permalink to &quot;Creating a backup&quot;">​</a></h2><p>Choose <strong>Download backup archive</strong> to save a single archive of your camera.ui storage directory: configuration, database, user accounts, and media. Keep it somewhere safe.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><h2 id="restoring" tabindex="-1">Restoring <a class="header-anchor" href="#restoring" aria-label="Permalink to &quot;Restoring&quot;">​</a></h2><p>Upload an archive and choose <strong>Restore backup archive</strong>, then confirm with <strong>Restore and restart</strong>. This replaces the current configuration, so be sure you want to roll back to the archive&#39;s state.</p><p>A <strong>Restoring backup</strong> overlay covers the screen while it works and walks through three steps: uploading the archive (with a progress bar), restoring, and restarting the server. Leave the window open until it&#39;s done. camera.ui logs you out at the end, so sign in again once the server is back.</p><p>Archives larger than 200 MB are rejected on upload. If yours is too big, exclude media folders from the backup and create a new one.<sup class="footnote-ref"><a href="#fn1" id="fnref1:1">[1:1]</a></sup></p><h2 id="scheduled-backups" tabindex="-1">Scheduled backups <a class="header-anchor" href="#scheduled-backups" aria-label="Permalink to &quot;Scheduled backups&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/admin/backup-scheduler.png",
    alt: "The Backup scheduler card"
  }, null, _parent));
  _push(`<p>The <strong>Backup scheduler</strong> card creates backups automatically and keeps only the newest archives.</p><p>Turn on the toggle, then set:</p><ul><li><strong>Frequency.</strong> Daily, Weekly, or Monthly.</li><li><strong>Time.</strong> The time of day the backup runs, as HH:mm (default <code>03:00</code>).</li><li><strong>Weekday.</strong> Shown only when Frequency is Weekly.</li><li><strong>Day of month.</strong> Shown only when Frequency is Monthly, 1-28.</li><li><strong>Keep backups.</strong> How many of the newest archives to retain, 1-60 (default 7). Older archives are deleted automatically after each run.</li><li><strong>Destination folder.</strong> An absolute path on the server, for example a NAS mount. Leave it empty to use the default folder inside your storage directory. A relative path is rejected.</li></ul><p>Use <strong>Run now</strong> to trigger a backup immediately without waiting for the schedule. A <strong>Last run</strong> line shows the timestamp and result (success or error) of the most recent scheduled run, or &quot;never&quot; if none has run yet.</p><p>Scheduled archives are written to the destination folder on the server, unlike a manual download, which saves the archive to your browser. Everything the scheduler has created appears under <strong>Available backups</strong>, with the filename, date, and size, and a Download or Remove action for each entry.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>To exclude a folder from the backup (for example a large media folder), place an empty file named <code>.backupignore</code> in it. <a href="#fnref1" class="footnote-backref">↩︎</a> <a href="#fnref1:1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("admin/backup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const backup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  backup as default
};
