import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Backup & Wiederherstellung","description":"","frontmatter":{"title":"Backup & Wiederherstellung"},"headers":[],"relativePath":"de/admin/backup.md","filePath":"de/admin/backup.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "de/admin/backup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/admin/backup.md for this page in Markdown format</div><h1 id="backup-wiederherstellung" tabindex="-1">Backup &amp; Wiederherstellung <a class="header-anchor" href="#backup-wiederherstellung" aria-label="Permalink to &quot;Backup &amp; Wiederherstellung&quot;">​</a></h1><p>Du kannst dein camera.ui-Setup sichern und später wiederherstellen, auf jeder Plattform. Es liegt unter <strong>Einstellungen → Backup</strong> (nur Admins).</p><h2 id="ein-backup-erstellen" tabindex="-1">Ein Backup erstellen <a class="header-anchor" href="#ein-backup-erstellen" aria-label="Permalink to &quot;Ein Backup erstellen&quot;">​</a></h2><p>Wähle <strong>Backup-Archiv herunterladen</strong>, um ein einzelnes Archiv deines camera.ui-Speicherverzeichnisses zu speichern: Konfiguration, Datenbank, Benutzerkonten und Medien. Bewahre es sicher auf.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><h2 id="wiederherstellen" tabindex="-1">Wiederherstellen <a class="header-anchor" href="#wiederherstellen" aria-label="Permalink to &quot;Wiederherstellen&quot;">​</a></h2><p>Lade ein Archiv hoch und wähle <strong>Backup-Archiv wiederherstellen</strong>, bestätige dann mit <strong>Wiederherstellen und neustarten</strong>. Das ersetzt die aktuelle Konfiguration, sei dir also sicher, dass du auf den Stand des Archivs zurück willst.</p><p>Während der Wiederherstellung liegt die Überlagerung <strong>Backup wiederherstellen</strong> über dem Bildschirm und durchläuft drei Schritte: Archiv hochladen (mit Fortschrittsbalken), wiederherstellen und Server neu starten. Lass das Fenster offen, bis es fertig ist. camera.ui meldet dich am Ende ab, melde dich also neu an, sobald der Server wieder da ist.</p><p>Archive größer als 200 MB werden beim Hochladen abgelehnt. Ist deins zu groß, schließe Medienordner vom Backup aus und erstelle ein neues.<sup class="footnote-ref"><a href="#fn1" id="fnref1:1">[1:1]</a></sup></p><h2 id="geplante-backups" tabindex="-1">Geplante Backups <a class="header-anchor" href="#geplante-backups" aria-label="Permalink to &quot;Geplante Backups&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/admin/backup-scheduler.png",
    alt: 'Die Karte „Backup-Zeitplan"'
  }, null, _parent));
  _push(`<p>Die Karte <strong>Backup-Zeitplan</strong> erstellt Backups automatisch und behält nur die neuesten Archive.</p><p>Schalte den Umschalter ein und lege dann fest:</p><ul><li><strong>Häufigkeit.</strong> Täglich, Wöchentlich oder Monatlich.</li><li><strong>Uhrzeit.</strong> Die Tageszeit, zu der das Backup läuft, im Format HH:mm (Standard <code>03:00</code>).</li><li><strong>Wochentag.</strong> Wird nur angezeigt, wenn Häufigkeit auf Wöchentlich steht.</li><li><strong>Tag des Monats.</strong> Wird nur angezeigt, wenn Häufigkeit auf Monatlich steht, 1-28.</li><li><strong>Backups behalten.</strong> Wie viele der neuesten Archive behalten werden, 1-60 (Standard 7). Ältere Archive werden nach jedem Lauf automatisch gelöscht.</li><li><strong>Zielordner.</strong> Ein absoluter Pfad auf dem Server, zum Beispiel ein NAS-Mount. Leer lassen, um den Standardordner innerhalb deines Speicherverzeichnisses zu verwenden. Ein relativer Pfad wird abgelehnt.</li></ul><p>Mit <strong>Jetzt ausführen</strong> löst du ein Backup sofort aus, ohne auf den Zeitplan zu warten. Eine Zeile <strong>Letzter Lauf</strong> zeigt Zeitstempel und Ergebnis (Erfolg oder Fehler) des letzten geplanten Laufs, oder &quot;nie&quot;, wenn noch keiner gelaufen ist.</p><p>Geplante Archive werden im Zielordner auf dem Server gespeichert, im Unterschied zu einem manuellen Download, der das Archiv im Browser speichert. Alles, was der Zeitplan erstellt hat, erscheint unter <strong>Vorhandene Backups</strong>, mit Dateiname, Datum und Größe sowie einer Download- oder Entfernen-Aktion je Eintrag.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Um einen Ordner vom Backup auszuschließen (zum Beispiel einen großen Medienordner), lege darin eine leere Datei mit dem Namen <code>.backupignore</code> an. <a href="#fnref1" class="footnote-backref">↩︎</a> <a href="#fnref1:1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/admin/backup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const backup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  backup as default
};
