import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Dashboard-Karten","description":"","frontmatter":{"title":"Dashboard-Karten"},"headers":[],"relativePath":"de/home-assistant/card.md","filePath":"de/home-assistant/card.md","lastUpdated":1784589260000}');
const _sfc_main = { name: "de/home-assistant/card.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/home-assistant/card.md for this page in Markdown format</div><h1 id="dashboard-karten" tabindex="-1">Dashboard-Karten <a class="header-anchor" href="#dashboard-karten" aria-label="Permalink to &quot;Dashboard-Karten&quot;">​</a></h1><p>Die camera.ui-Integration bringt zwei eigene Lovelace-Karten für deine Home-Assistant-Dashboards mit:</p><ul><li><strong>camera.ui Card.</strong> Eine Live-Ansicht für eine einzelne Kamera.</li><li><strong>camera.ui Grid.</strong> Ein Raster aus Live-Kacheln, klick eine Kachel an, um live zu gehen.</li></ul><p>Beide Karten streamen über Home Assistant, zeigen ein Snapshot-Standbild bis du live gehst, und bieten Steuerung für Auflösung, Transport und PTZ, sofern die Kamera das unterstützt.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/home-assistant/card.png",
    alt: "camera.ui-Einzelkamera-Karte mit Live-Stream und Player-Steuerung"
  }, null, _parent));
  _push(`<h2 id="bevor-du-startest" tabindex="-1">Bevor du startest <a class="header-anchor" href="#bevor-du-startest" aria-label="Permalink to &quot;Bevor du startest&quot;">​</a></h2><p>Richte zuerst die <a href="/de/home-assistant/integration">camera.ui-Integration</a> ein. Beim Laden der Integration wird das Karten-Bundle bereitgestellt und für dich als Lovelace-Ressource registriert. Ein manueller Ressourcen-Schritt entfällt: Die Karten stehen im Karten-Picker zur Verfügung, sobald die Integration läuft.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><h2 id="karte-hinzufugen" tabindex="-1">Karte hinzufügen <a class="header-anchor" href="#karte-hinzufugen" aria-label="Permalink to &quot;Karte hinzufügen&quot;">​</a></h2><ol><li>Öffne ein Dashboard, wähle <strong>Dashboard bearbeiten</strong> und dann <strong>Karte hinzufügen</strong>.</li><li>Suche im Karten-Picker nach <strong>camera.ui Card</strong> oder <strong>camera.ui Grid</strong>.</li><li>Wähle die Karte, setze die Entität (oder die Kameraliste beim Grid) und speichere.</li></ol><p>Du kannst eine Karte auch im YAML-Modus hinzufügen. Die <code>type:</code>-Werte der Karten sind <code>cameraui-card</code> und <code>cameraui-grid-card</code>.</p><p>Die Einzel-Card prüft ihre Entität und zeigt statt eines Streams eine Meldung, wenn etwas nicht passt: <strong>No entity configured</strong>, <strong>Entity not found</strong> oder <strong>Not a camera.ui camera entity</strong>, falls die Entität keine camera.ui-Kamera ist. Die Grid-Card überspringt jede Entität, die sie nicht auflösen kann, und zeigt <strong>No cameras configured</strong>, wenn keine übrig bleibt.</p><h2 id="camera-ui-card" tabindex="-1">camera.ui Card <a class="header-anchor" href="#camera-ui-card" aria-label="Permalink to &quot;camera.ui Card&quot;">​</a></h2><p>Die Karte für eine einzelne Kamera. <code>entity</code> ist erforderlich.</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">cameraui-card</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">entity</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.front_door</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">title</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">Haustür</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">source</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">high-resolution</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">auto</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">autostart</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">snapshot_interval</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">10</span></span></code></pre></div><p>Optionen:</p><ul><li><strong>entity.</strong> Erforderlich. Die camera.ui-Kamera-Entität, die angezeigt werden soll.</li><li><strong>title.</strong> Titel im Overlay. Standard ist der Anzeigename oder Kameraname der Entität.</li><li><strong>source.</strong> Auf welcher Auflösungsrolle gestartet wird: <code>high-resolution</code>, <code>mid-resolution</code> oder <code>low-resolution</code>. Standard ist <code>high-resolution</code>.</li><li><strong>mode.</strong> Streaming-Transport: <code>auto</code>, <code>webrtc</code> oder <code>mse</code>. Standard ist <code>auto</code>, das WebRTC oder MSE für dich auswählt.</li><li><strong>autostart.</strong> Sofort live gehen, statt zuerst das Standbild zu zeigen. Standard ist <code>false</code>.</li><li><strong>snapshot_interval.</strong> Wie oft das Snapshot-Standbild aktualisiert wird, in Sekunden. Standard <code>10</code>, Minimum <code>2</code>.</li></ul><h2 id="camera-ui-grid" tabindex="-1">camera.ui Grid <a class="header-anchor" href="#camera-ui-grid" aria-label="Permalink to &quot;camera.ui Grid&quot;">​</a></h2><p>Die Grid-Karte zeigt mehrere Kameras als Live-Kacheln. <code>cameras</code> ist erforderlich.</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">cameraui-grid-card</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">cameras</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.front_door</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.driveway</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.garden</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">columns</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">3</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">source</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">high-resolution</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">auto</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">autostart</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span></code></pre></div><p>Optionen:</p><ul><li><strong>cameras.</strong> Erforderlich. Eine Liste von camera.ui-Kamera-entity_ids.</li><li><strong>columns.</strong> Anzahl der Spalten. Lässt du sie weg, nutzt das Raster 1 Spalte für eine einzelne Kamera, 2 für bis zu vier, und 3 darüber.</li><li><strong>source, mode, autostart.</strong> Gleiche Bedeutung wie bei der Einzelkarte, angewendet auf jede Kachel.</li></ul><h2 id="streaming" tabindex="-1">Streaming <a class="header-anchor" href="#streaming" aria-label="Permalink to &quot;Streaming&quot;">​</a></h2><p>Die Karte zeigt ein Snapshot-Standbild, bis du live gehst. Ein kleines Badge unten links zeigt, wie alt der Snapshot ist (<code>Jetzt</code>, Sekunden, Minuten oder Stunden). Klick den Play-Button, oder setze <code>autostart: true</code>, um den Live-Stream zu öffnen.</p><p>Der Live-Stream läuft über die Streaming-Engine per WebRTC oder MSE, geproxyt durch Home Assistant, sodass nichts direkt nach außen freigegeben werden muss. Mit <code>mode: auto</code> wählt die Karte den Transport; über das Modus-Pill kannst du während des Ansehens <strong>AUTO → WebRTC → MSE</strong> durchschalten. H.265-Kameras werden ebenfalls unterstützt.<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup></p><p>Hat eine Kamera mehr als eine Auflösungsrolle, schaltet ein Auflösungs-Pill zwischen <strong>HD</strong>, <strong>MD</strong> und <strong>SD</strong> um. Beim Überfahren mit der Maus erscheinen die Steuerelemente: Pause und Play, Stummschalten, Bild-in-Bild und Vollbild. Schmale Karten blenden die zusätzlichen Steuerelemente aus, damit das Video frei bleibt.<sup class="footnote-ref"><a href="#fn3" id="fnref3">[3]</a></sup></p><h2 id="ptz-steuerung" tabindex="-1">PTZ-Steuerung <a class="header-anchor" href="#ptz-steuerung" aria-label="Permalink to &quot;PTZ-Steuerung&quot;">​</a></h2><p>Kameras mit PTZ erhalten ein Overlay über dem Video, sobald die Karte breit genug ist: einen Zoom-Schieber links und ein Pan/Tilt-Pad rechts. Ein gehaltenes Steuerelement sendet eine kontinuierliche Bewegung; beim Loslassen stoppt sie. Hat die Kamera ein Home-Preset, sendet ein Tippen auf das Pad sie zur Home-Position. Das Overlay zeigt nur die Steuerelemente, die die Kamera tatsächlich unterstützt.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/home-assistant/card-ptz.png",
    alt: "camera.ui-Karte mit PTZ-Overlay: Zoom-Schieber und Pan/Tilt-Pad"
  }, null, _parent));
  _push(`<p>Im Hintergrund ruft das Overlay den Dienst <code>cameraui.ptz</code> auf, sodass du dieselbe Kamera auch aus deinen eigenen Automationen steuern kannst.</p><h2 id="was-die-karten-nicht-konnen" tabindex="-1">Was die Karten nicht können <a class="header-anchor" href="#was-die-karten-nicht-konnen" aria-label="Permalink to &quot;Was die Karten nicht können&quot;">​</a></h2><p>Die Karten sind reine Live-Ansicht. Sie zeichnen keine Erkennungs-Boxen oder Objekt-Sensor-Badges, und es gibt keine Aufnahmen- oder Ereignis-Timeline in der Karte. Für Objekt-Sensoren, Geräte-Trigger und das <code>cameraui_event</code>-Bus-Ereignis siehe die <a href="/de/home-assistant/integration">Integrations-Seite</a>.</p><h2 id="nachste-schritte" tabindex="-1">Nächste Schritte <a class="header-anchor" href="#nachste-schritte" aria-label="Permalink to &quot;Nächste Schritte&quot;">​</a></h2><ul><li><strong><a href="/de/home-assistant/integration">Home-Assistant-Integration</a></strong> — Integration, Objekt-Sensoren und Automationen einrichten.</li></ul><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>In Dashboards im Speicher-Modus legt die Integration die Lovelace-Ressource mit einer inhaltsgehashten URL an oder aktualisiert sie. In Dashboards im YAML-Modus wird das Skript stattdessen für die Sitzung eingefügt. So oder so fügst du keine Ressource von Hand hinzu. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li><li id="fn2" class="footnote-item"><p>Das Stream-Backend ist go2rtc, geproxyt durch Home Assistant. Die Codec-Verarbeitung, inklusive H.265, liegt in der gemeinsam genutzten Streaming-Komponente, die die Karte einbettet. <a href="#fnref2" class="footnote-backref">↩︎</a></p></li><li id="fn3" class="footnote-item"><p>Die Pills werden unter 300px Kartenbreite ausgeblendet, Bild-in-Bild unter 260px, Stummschalten unter 200px, und das PTZ-Overlay braucht mindestens 340px. <a href="#fnref3" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/home-assistant/card.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const card = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  card as default
};
