import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Desktop-App","description":"","frontmatter":{},"headers":[],"relativePath":"de/install/desktop.md","filePath":"de/install/desktop.md","lastUpdated":1784139260000}');
const _sfc_main = { name: "de/install/desktop.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/install/desktop.md for this page in Markdown format</div><h1 id="desktop-app" tabindex="-1">Desktop-App <a class="header-anchor" href="#desktop-app" aria-label="Permalink to &quot;Desktop-App&quot;">​</a></h1><p>Die Desktop-App ist die empfohlene Art, camera.ui auf <strong>macOS und Windows</strong> zu betreiben. Ein Download installiert Server und Viewer zusammen, sodass du mit wenigen Klicks ein laufendes Setup hast. Sie läuft auch auf Linux, dort ist allerdings ein <a href="/de/install/docker">Docker</a>- oder <a href="/de/install/proxmox">Proxmox</a>-Server die bessere Wahl (siehe <a href="/de/install/">Welche Installation?</a>).</p><h2 id="download" tabindex="-1">Download <a class="header-anchor" href="#download" aria-label="Permalink to &quot;Download&quot;">​</a></h2><p>Lade den Installer für deine Plattform herunter, direkt hier oder von der <a href="https://cameraui.com/#download" target="_blank" rel="noreferrer">Download-Seite</a>. Die Links zeigen immer auf das neueste Release.</p><table tabindex="0"><thead><tr><th>Plattform</th><th>Download</th></tr></thead><tbody><tr><td>macOS (Apple Silicon)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-arm64.dmg" target="_blank" rel="noreferrer"><code>camera.ui-arm64.dmg</code></a></td></tr><tr><td>macOS (Intel)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x64.dmg" target="_blank" rel="noreferrer"><code>camera.ui-x64.dmg</code></a></td></tr><tr><td>Windows 10 / 11</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x64.exe" target="_blank" rel="noreferrer"><code>camera.ui-x64.exe</code></a></td></tr><tr><td>Linux (AppImage)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x86_64.AppImage" target="_blank" rel="noreferrer"><code>x64</code></a> · <a href="https://downloads.cameraui.com/latest/camera.ui-arm64.AppImage" target="_blank" rel="noreferrer"><code>arm64</code></a></td></tr><tr><td>Linux (.deb)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-amd64.deb" target="_blank" rel="noreferrer"><code>amd64</code></a> · <a href="https://downloads.cameraui.com/latest/camera.ui-arm64.deb" target="_blank" rel="noreferrer"><code>arm64</code></a></td></tr></tbody></table><p>Apple-Silicon- und Intel-Macs nutzen getrennte Downloads. Wähle den, der zu deinem Mac passt.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-download.png",
    alt: "camera.ui Download-Seite"
  }, null, _parent));
  _push(`<h2 id="installieren" tabindex="-1">Installieren <a class="header-anchor" href="#installieren" aria-label="Permalink to &quot;Installieren&quot;">​</a></h2><h3 id="macos" tabindex="-1">macOS <a class="header-anchor" href="#macos" aria-label="Permalink to &quot;macOS&quot;">​</a></h3><p>Öffne die heruntergeladene <code>.dmg</code> und ziehe <strong>camera.ui</strong> in deinen Programme-Ordner, dann starte es von dort. Die App ist von Apple signiert und notarisiert, sie öffnet sich also ohne zusätzliche Warnungen.</p><h3 id="windows" tabindex="-1">Windows <a class="header-anchor" href="#windows" aria-label="Permalink to &quot;Windows&quot;">​</a></h3><p>Führe die heruntergeladene <code>.exe</code> aus. Der Installer lässt dich den Installationsort wählen und richtet die App für den aktuellen Benutzer ein, sodass keine Administratorrechte nötig sind.</p><p>Windows zeigt möglicherweise eine <strong>SmartScreen</strong>-Warnung, weil die App noch nicht code-signiert ist. Wähle <strong>Weitere Informationen → Trotzdem ausführen</strong>, um fortzufahren.</p><h3 id="linux" tabindex="-1">Linux <a class="header-anchor" href="#linux" aria-label="Permalink to &quot;Linux&quot;">​</a></h3><p>Installiere die <code>.deb</code> mit deinem Paketmanager:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">sudo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> apt</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./camera.ui-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">.deb</span></span></code></pre></div><p>Oder mache die <code>.AppImage</code> ausführbar und starte sie:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">chmod</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> +x</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> camera.ui-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">.AppImage</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">./camera.ui-*.AppImage</span></span></code></pre></div><div class="tip custom-block"><p class="custom-block-title">Nimm die <code>.AppImage</code>, wenn du automatische Updates willst</p><p>Nur die <code>.AppImage</code> aktualisiert sich selbst. Eine <code>.deb</code>-Installation bleibt auf ihrer Version. Aktualisiere sie, indem du die neue <code>.deb</code> herunterlädst und installierst.</p></div><h2 id="erster-start-wahlen-wie-es-lauft" tabindex="-1">Erster Start: wählen, wie es läuft <a class="header-anchor" href="#erster-start-wahlen-wie-es-lauft" aria-label="Permalink to &quot;Erster Start: wählen, wie es läuft&quot;">​</a></h2><p>Beim ersten Öffnen fragt die App <strong>„Wie soll camera.ui laufen?&quot;</strong> und bietet vier Modi:</p><ul><li><strong>Server.</strong> Betreibt den camera.ui-Server auf diesem Gerät. Das ist die All-in-One-Option und das, was die meisten auf macOS und Windows wählen.</li><li><strong>Worker.</strong> Übernimmt einen Teil der Arbeit für einen anderen camera.ui-Server in deinem Netzwerk. Gib die Adresse des Hauptservers und einen Pairing-Code aus dessen <strong>Workers</strong>-Einstellungen ein. Siehe <a href="/de/admin/workers#worker-mit-der-desktop-app">Worker</a>.</li><li><strong>Viewer · Direkt.</strong> Verbindet sich per Adresse mit einem vorhandenen Server, zum Beispiel einer anderen Maschine in deinem Netzwerk.</li><li><strong>Viewer · Cloud.</strong> Meldet sich über cloud.cameraui.com an, um einen Server über <a href="/de/remote/cloud">camera.ui Cloud</a> zu erreichen.</li></ul>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-mode-picker.png",
    alt: "Erststart-Modus-Auswahl der Desktop-App"
  }, null, _parent));
  _push(`<p>Im <strong>Server</strong>-Modus startet die App den Server, öffnet die Oberfläche und führt dich durch die <a href="/de/intro/getting-started">Ersteinrichtung</a>. In einem <strong>Viewer</strong>-Modus verbindet sie sich mit einem Server, den du bereits hast. Im <strong>Worker</strong>-Modus gibt es kein Fenster, nur das Tray-Symbol und eine Statusanzeige.</p><h2 id="das-tray-symbol" tabindex="-1">Das Tray-Symbol <a class="header-anchor" href="#das-tray-symbol" aria-label="Permalink to &quot;Das Tray-Symbol&quot;">​</a></h2><p>Im Tray-Symbol stecken die Einstellungen der App selbst:</p><ul><li><strong>Öffnen.</strong> Holt das Fenster zurück.</li><li><strong>Beim Anmelden öffnen.</strong> Startet camera.ui, sobald du dich anmeldest. Es landet direkt im Tray: kein Fenster, kein Splash. Öffne es bei Bedarf über das Tray-Symbol.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></li><li><strong>In den Tray schließen.</strong> Standardmäßig aus. Schaltest du es ein, wird das Fenster beim Schließen nur versteckt, ein Server auf diesem Gerät läuft also weiter.<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup></li><li><strong>Modus wechseln….</strong> Ändert, wie die App läuft, ohne Neuinstallation.</li><li><strong>Beenden.</strong> Stoppt die App, im Server-Modus auch den Server.</li></ul><p>Unter Windows öffnet ein Linksklick auf das Tray-Symbol das Fenster, ein Rechtsklick das Menü.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-tray-menu.png",
    alt: "Tray-Menü der Desktop-App"
  }, null, _parent));
  _push(`<h2 id="macos-berechtigungen" tabindex="-1">macOS-Berechtigungen <a class="header-anchor" href="#macos-berechtigungen" aria-label="Permalink to &quot;macOS-Berechtigungen&quot;">​</a></h2><p>Auf macOS 15 und neuer fragt das System beim ersten Start nach Zugriff auf das <strong>lokale Netzwerk</strong>. Erlaube ihn, sonst kann die App deine Kameras im Netzwerk nicht erreichen. Beim ersten Gegensprechen fragt macOS zusätzlich nach <strong>Mikrofon</strong>-Zugriff, und beim ersten Tippen auf <strong>„Mein Standort&quot;</strong> beim Geofence-Trigger in den <a href="/de/automations/">Automatisierungen</a> fragt es nach <strong>Standort</strong>-Zugriff.</p><h2 id="updates" tabindex="-1">Updates <a class="header-anchor" href="#updates" aria-label="Permalink to &quot;Updates&quot;">​</a></h2><p>Die Desktop-App hält sich selbst aktuell. Sie prüft beim Start und regelmäßig im Betrieb auf Updates und lädt sie dann für dich herunter und installiert sie. Im Server-Modus aktualisiert sie außerdem den gebündelten Server, bevor sie ihn startet, sodass App und Server synchron bleiben.</p><p>Eine Ausnahme unter Linux: nur die <code>.AppImage</code> aktualisiert sich selbst. Wenn du die <code>.deb</code> installiert hast, aktualisiere sie, indem du die neue <code>.deb</code> von der <a href="https://cameraui.com" target="_blank" rel="noreferrer">Download-Seite</a> herunterlädst und installierst.</p><h2 id="wo-deine-daten-liegen" tabindex="-1">Wo deine Daten liegen <a class="header-anchor" href="#wo-deine-daten-liegen" aria-label="Permalink to &quot;Wo deine Daten liegen&quot;">​</a></h2><p>Im Server-Modus werden deine Einstellungen und Aufnahmen in einem <code>camera.ui/volume</code>-Ordner innerhalb des benutzerbezogenen Datenordners der App gespeichert:</p><ul><li><strong>macOS:</strong> <code>~/Library/Application Support/camera.ui/camera.ui/volume</code></li><li><strong>Windows:</strong> <code>%APPDATA%\\camera.ui\\camera.ui\\volume</code></li><li><strong>Linux:</strong> <code>~/.config/camera.ui/camera.ui/volume</code></li></ul><p>Siehe <a href="/de/admin/backup">Backup &amp; Wiederherstellung</a>, um eine Kopie zu behalten.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Nur macOS und Windows. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li><li id="fn2" class="footnote-item"><p>Nur Windows und Linux. Unter macOS bleibt die App beim Schließen des Fensters ohnehin im Tray, daher gibt es die Option dort nicht. <a href="#fnref2" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/install/desktop.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const desktop = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  desktop as default
};
