import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Plugins","description":"","frontmatter":{"title":"Plugins"},"headers":[],"relativePath":"de/plugins/index.md","filePath":"de/plugins/index.md","lastUpdated":1784589260000}');
const _sfc_main = { name: "de/plugins/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/plugins.md for this page in Markdown format</div><h1 id="plugins" tabindex="-1">Plugins <a class="header-anchor" href="#plugins" aria-label="Permalink to &quot;Plugins&quot;">​</a></h1><p>Plugins erweitern camera.ui. Das meiste, was es über die Live-Ansicht hinaus kann, stammt von Plugins, die du installierst: die <a href="/de/detection/">KI-Backends und Bewegungs-Engines</a>, die die Erkennung antreiben, Audio-Erkennung, Smart-Home-Bridges wie <a href="/de/plugins/homekit">HomeKit</a> und Integrationen für verschiedene Kamera-Marken. Plugins zu verwalten ist eine Admin-Aufgabe.</p><h2 id="zwei-dinge-getrennt-gehalten" tabindex="-1">Zwei Dinge, getrennt gehalten <a class="header-anchor" href="#zwei-dinge-getrennt-gehalten" aria-label="Permalink to &quot;Zwei Dinge, getrennt gehalten&quot;">​</a></h2><ul><li><strong>Ein Plugin installieren</strong> fügt es deinem Server hinzu, einmalig. Darum geht es in diesem Abschnitt.</li><li><strong>Ein Plugin zuweisen</strong> entscheidet, welche Kamera es nutzt, etwa welche Bewegungs-Engine eine Kamera fährt. Das geschieht pro Kamera, in <a href="/de/sensors/setup">Sensoren einrichten</a>.</li></ul><h2 id="plugins-verwalten" tabindex="-1">Plugins verwalten <a class="header-anchor" href="#plugins-verwalten" aria-label="Permalink to &quot;Plugins verwalten&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/plugins/plugins-list.png",
    alt: "Die Plugins-Seite"
  }, null, _parent));
  _push(`<p>Öffne <strong>Plugins</strong> aus dem Menü, um alles Installierte zu sehen, jeweils als Karte mit Live-Status (Bereit, Gestartet, Gestoppt, Fehler). Von einer Karte aus kannst du:</p><ul><li>Es <strong>aktivieren oder deaktivieren</strong> und seinen Prozess <strong>starten, stoppen oder neu starten</strong>.</li><li>Es <strong>aktualisieren</strong>, wenn eine neue Version verfügbar ist, oder eine <strong>bestimmte Version</strong> wählen.</li><li>Seine <strong>Einstellungen öffnen</strong> oder seine <strong>Logs</strong> ansehen, wenn etwas klemmt.</li><li>Es <strong>deinstallieren</strong>, optional samt gespeicherter Daten.</li></ul><p>Aufnahmen sind die Ausnahme: Wenn du die gespeicherten Daten eines Aufnahme-Plugins löschst, bleibt das Videomaterial erhalten.</p><p>Der Zahnrad-Button neben der Suchleiste enthält zwei Einstellungen, beide standardmäßig aus:</p><ul><li><strong>Beta-Versionen.</strong> Zeigt Vorabversionen in der Versionsauswahl und bietet Beta-Releases als Updates an.</li><li><strong>Plugin-Build-Skripte erlauben.</strong> Lässt Plugins beim Installieren oder Aktualisieren Install-Skripte und native Builds ausführen. Nur für Plugins aktivieren, denen du vertraust.</li></ul><p>Plugins laufen als eigener Prozess, sodass ein sich fehlverhaltendes Plugin nicht den Rest mitreißt. Sie können in Node, Python oder Go geschrieben sein; ein kleines Abzeichen auf jeder Karte zeigt, welche.</p><h2 id="ein-plugin-installieren" tabindex="-1">Ein Plugin installieren <a class="header-anchor" href="#ein-plugin-installieren" aria-label="Permalink to &quot;Ein Plugin installieren&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/plugins/plugin-store.png",
    alt: "Der Plugin-Store"
  }, null, _parent));
  _push(`<p>Wähle <strong>Plugins suchen</strong>, um den Store zu öffnen. Die Liste stammt von npm, sodass jedes als camera.ui-Plugin veröffentlichte Paket erscheinen kann und der Katalog keine feste Liste ist, aber camera.ui kuratiert darüber, was du siehst:</p><ul><li><strong>Vertrauen.</strong> Jedes Plugin ist als <strong>Offiziell</strong> (von camera.ui veröffentlicht), <strong>Verifiziert</strong> (ein vom camera.ui-Team geprüftes Community-Plugin) oder <strong>Community</strong> (von beliebigen Personen veröffentlicht, nicht geprüft) gekennzeichnet. Du kannst nach Vertrauensstufe filtern.</li><li><strong>Sicherheit.</strong> Als bösartig oder kompromittiert bekannte Plugins werden blockiert: Sie erscheinen nicht, lassen sich nicht installieren, und ein bereits installiertes wird automatisch deaktiviert, falls es später blockiert wird.</li><li><strong>Durchsuchen.</strong> Filtere nach Kategorie, starte bei den empfohlenen Plugins und sortiere nach Name, wöchentlichen Downloads oder letzter Aktualisierung. Jeder Eintrag zeigt sein Logo, eine kurze Beschreibung und seine Download-Zahlen.</li></ul><p>Wähle ein Plugin und installiere es, bei Bedarf mit Versionswahl. Einmal installiert, aktiviere es und weise es zu, wo es gebraucht wird.</p><h2 id="einstellungen" tabindex="-1">Einstellungen <a class="header-anchor" href="#einstellungen" aria-label="Permalink to &quot;Einstellungen&quot;">​</a></h2><p>Die eigenen Einstellungen eines Plugins liegen auf seiner Seite unter <strong>Einstellungen</strong> und gelten serverweit. Einstellungen, die eine einzelne Kamera betreffen, werden stattdessen in den <a href="/de/cameras/settings">Einstellungen dieser Kamera</a> bearbeitet. Aufnahme-Plugin-Einstellungen liegen beim Rest der <a href="/de/recording/">Aufnahmen</a>.</p><h2 id="einrichtungs-anleitungen" tabindex="-1">Einrichtungs-Anleitungen <a class="header-anchor" href="#einrichtungs-anleitungen" aria-label="Permalink to &quot;Einrichtungs-Anleitungen&quot;">​</a></h2><ul><li><strong><a href="/de/plugins/homekit">HomeKit</a></strong> — deine Kameras zu Apple Home hinzufügen.</li><li><strong><a href="/de/home-assistant/">Home Assistant</a></strong> — Kameras, Sensoren und Erkennungs-Events als Home-Assistant-Entitäten.</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/plugins/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
