import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Aufnahmen (NVR)","description":"","frontmatter":{"title":"Aufnahmen (NVR)"},"headers":[],"relativePath":"de/recording/index.md","filePath":"de/recording/index.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "de/recording/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/recording.md for this page in Markdown format</div><h1 id="aufnahmen-nvr" tabindex="-1">Aufnahmen (NVR) <a class="header-anchor" href="#aufnahmen-nvr" aria-label="Permalink to &quot;Aufnahmen (NVR)&quot;">​</a></h1><p>camera.ui nimmt deine Kameras auf, damit du zurückschauen kannst, was passiert ist. Aufnahmen und alles in diesem Abschnitt erfordern ein aktives camera.ui-Abo.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><div class="info custom-block"><p class="custom-block-title">Aufnahmen während der Beta testen</p><p>Abos sind noch nicht käuflich. Um Aufnahmen zu testen, erstelle dein camera.ui-Konto auf <a href="https://cloud.cameraui.com/" target="_blank" rel="noreferrer">cloud.cameraui.com</a> und frag auf unserem <a href="https://discord.gg/bBGnGcbz8N" target="_blank" rel="noreferrer">Discord</a> nach einem Trial.</p></div><h2 id="aufnahmen-aktivieren" tabindex="-1">Aufnahmen aktivieren <a class="header-anchor" href="#aufnahmen-aktivieren" aria-label="Permalink to &quot;Aufnahmen aktivieren&quot;">​</a></h2><p>Aufnahmen kommen vom <strong>camera.ui NVR</strong>-Plugin (standardmäßig installiert) und laufen über ein Abo, das an dein camera.ui-Konto gebunden ist. So schaltest du sie frei:</p><ol><li>Wähle in <strong>Einstellungen → Remote Zugriff</strong> den Button <strong>Server registrieren</strong> und melde dich mit deinem camera.ui-Konto an. Das verknüpft den Server mit deinem Konto; den Remote-Cloud-Zugriff musst du dafür nicht aktivieren.</li><li>Öffne <strong>Einstellungen → Aufnahmen</strong> und klicke in der Karte <strong>Lizenz &amp; Cloud</strong> auf das <strong>Cloud-Icon</strong> und melde dich an. Grau heißt nicht verbunden, grün heißt verbunden.</li><li>Deine Lizenz aktiviert sich dann automatisch. Aktualisiert sich der Status nicht, nutze den <strong>Refetch License</strong>-Button.</li></ol><p>Sobald die Lizenz aktiv ist, nehmen neu hinzugefügte Kameras von selbst auf, solange dein Abo noch einen freien Kamera-Slot hat. Eine neue Kamera nimmt durchgehend in allen Stream-Qualitäten auf. Du kannst den Modus ändern, auswählen, welche Qualitäten aufgenommen werden, oder die Aufnahme in den Aufnahme-Einstellungen der Kamera ausschalten.</p><h2 id="aufnahme-modi" tabindex="-1">Aufnahme-Modi <a class="header-anchor" href="#aufnahme-modi" aria-label="Permalink to &quot;Aufnahme-Modi&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/recording/recording-modes.png",
    alt: "Aufnahme-Modus-Einstellungen"
  }, null, _parent));
  _push(`<p>Jede Kamera nimmt in einem von drei Modi auf, einstellbar in ihren Aufnahme-Einstellungen:</p><ul><li><strong>Continuous.</strong> Nimmt rund um die Uhr auf. Du hast immer Material, brauchst aber am meisten Speicher.</li><li><strong>Event.</strong> Nimmt nur auf, wenn etwas passiert (Bewegung, ein Objekt, ein Sensor). Ein <strong>Pre-Buffer</strong> behält ein paar Sekunden vor jedem Auslöser, sodass du den Anlauf nicht verpasst.</li><li><strong>Ad-hoc.</strong> Verbindet sich nur mit der Kamera, wenn ein Ereignis auslöst. Nützlich für Kameras, die keine Ereignisse mehr senden, während ein Stream offen ist, etwa manche Batterie-Kameras.</li></ul><h2 id="qualitat" tabindex="-1">Qualität <a class="header-anchor" href="#qualitat" aria-label="Permalink to &quot;Qualität&quot;">​</a></h2><p>Du wählst, welche Stream-Qualitäten aufgenommen werden, <strong>high</strong>, <strong>mid</strong> oder <strong>low</strong>, und kannst mehrere behalten. Auch einen niedrig aufgelösten Stream aufzunehmen macht das Scrubben der <a href="/de/recording/timeline-playback">Timeline</a> schnell und flüssig.</p><h2 id="weiter" tabindex="-1">Weiter <a class="header-anchor" href="#weiter" aria-label="Permalink to &quot;Weiter&quot;">​</a></h2><ul><li><strong><a href="/de/recording/storage">Speicher &amp; Aufbewahrung</a></strong> — wo Aufnahmen liegen und wie lange sie behalten werden.</li><li><strong><a href="/de/recording/timeline-playback">Timeline &amp; Wiedergabe</a></strong> — Material durchsehen.</li><li><strong><a href="/de/recording/export">Export &amp; Download</a></strong> — einen Clip speichern.</li><li><strong><a href="/de/recording/browsing">Durchsuchen &amp; Filter</a></strong> — vergangene Ereignisse finden.</li></ul><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Aufnahmen (NVR) erfordern ein aktives camera.ui-Abo. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/recording/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
