import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"camera.ui Cloud","description":"","frontmatter":{"title":"camera.ui Cloud"},"headers":[],"relativePath":"de/remote/cloud.md","filePath":"de/remote/cloud.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "de/remote/cloud.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/remote/cloud.md for this page in Markdown format</div><h1 id="camera-ui-cloud" tabindex="-1">camera.ui Cloud <a class="header-anchor" href="#camera-ui-cloud" aria-label="Permalink to &quot;camera.ui Cloud&quot;">​</a></h1><p>camera.ui Cloud lässt dich deinen Server von überall erreichen, ohne am Router etwas zu ändern. Dein Server registriert sich bei der Cloud, und du verbindest dich über dein camera.ui-Konto. Das ist kostenlos und getrennt vom Aufnahme-Abo.</p><h2 id="dein-server-bleibt-deiner" tabindex="-1">Dein Server bleibt deiner <a class="header-anchor" href="#dein-server-bleibt-deiner" aria-label="Permalink to &quot;Dein Server bleibt deiner&quot;">​</a></h2><p>camera.ui Cloud ist ein Weg, deinen eigenen Server zu erreichen, keine Kopie davon. Deine Kameras, Aufnahmen, Einstellungen und die Oberfläche bleiben alle auf deinem Server. Die einzige Aufgabe der Cloud ist es, deiner App und deinem Server beim Verbinden zu helfen, und deine Session läuft dann direkt zu deiner eigenen Instanz. Dein Video, deine Zugangsdaten und andere Daten gehen direkt zu deinem Server und sind für camera.ui niemals einsehbar.</p><h2 id="aktivieren" tabindex="-1">Aktivieren <a class="header-anchor" href="#aktivieren" aria-label="Permalink to &quot;Aktivieren&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/remote/remote-settings.png",
    alt: "Die Cloud-Karte unter Einstellungen, Remote"
  }, null, _parent));
  _push(`<p>Öffne unter <strong>Einstellungen → Remote</strong> die <strong>Cloud</strong>-Karte und schalte <strong>Aktiviert</strong> ein. Gib dem Server einen <strong>Namen</strong>; so erscheint er in deinem Cloud-Dashboard, was praktisch ist, sobald du mehrere hast.</p><p>Die <strong>Status</strong>-Zeile zeigt, ob der Server <strong>Registriert</strong> ist, und eine <strong>Tunnel</strong>-Anzeige zeigt die Live-Verbindung. Um einen Server zu verbinden, wähle <strong>Server registrieren</strong> und schließe die Kopplung ab. Zeigt der Status <strong>Neu-Authentifizierung nötig</strong>, hat der Server seine Cloud-Zugangsdaten verloren: wähle <strong>Neu verbinden</strong> und koppel erneut. Einen registrierten Server nimmst du mit <strong>Server deregistrieren</strong> wieder aus deinem Konto. Denselben Ablauf auf dem Handy beschreibt <a href="/de/remote/pairing">Mobile Apps koppeln</a>.</p><h2 id="cloud-halt-die-direkte-verbindung-aktiv" tabindex="-1">Cloud hält die direkte Verbindung aktiv <a class="header-anchor" href="#cloud-halt-die-direkte-verbindung-aktiv" aria-label="Permalink to &quot;Cloud hält die direkte Verbindung aktiv&quot;">​</a></h2><p>Solange die Cloud aktiv ist, behält dein Server zusätzlich eine öffentliche Adresse, damit die Apps ihn erreichen. Deshalb ist der Schalter <strong>Aktiviert</strong> in der Karte <strong>Direkte Verbindung</strong> fest eingeschaltet, und die Zeile <strong>Externe URL</strong> zeigt die verwendete Adresse.</p><p>Wenn du keine direkte Adresse eingerichtet hast oder die konfigurierte nicht erreichbar ist, startet camera.ui stattdessen einen temporären Cloudflare-Tunnel. In beiden Fällen musst du am Router nichts ändern. Wenn du lieber deine eigene Adresse nutzt, richte sie unter <a href="/de/remote/">Direkte Verbindung</a> ein.</p><h2 id="das-cloud-dashboard" tabindex="-1">Das Cloud-Dashboard <a class="header-anchor" href="#das-cloud-dashboard" aria-label="Permalink to &quot;Das Cloud-Dashboard&quot;">​</a></h2><p>Mit der Anmeldung an deinem camera.ui-Konto bekommst du ein Dashboard, das alle deine registrierten Server beim Namen auflistet. Von dort wählst du einen Server zum Verbinden. Du kannst einen Server auch per Einladung mit einem anderen camera.ui-Konto <strong>teilen</strong>, sodass Familienmitglieder mit eigenem Login zugreifen.</p><h2 id="ausschalten" tabindex="-1">Ausschalten <a class="header-anchor" href="#ausschalten" aria-label="Permalink to &quot;Ausschalten&quot;">​</a></h2><p>Den Cloud-Zugriff zu deaktivieren beendet aktive Remote-Sitzungen. Lokale Verbindungen in deinem Netzwerk laufen weiter.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/remote/cloud.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const cloud = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  cloud as default
};
