import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Sensoren einrichten","description":"","frontmatter":{"title":"Sensoren einrichten"},"headers":[],"relativePath":"de/sensors/setup.md","filePath":"de/sensors/setup.md","lastUpdated":1785427198000}');
const _sfc_main = { name: "de/sensors/setup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /de/sensors/setup.md for this page in Markdown format</div><h1 id="sensoren-einrichten" tabindex="-1">Sensoren einrichten <a class="header-anchor" href="#sensoren-einrichten" aria-label="Permalink to &quot;Sensoren einrichten&quot;">​</a></h1><p>Die meisten Sensoren stammen von <a href="/de/plugins/">Plugins</a>. Um einer Kamera einen Sensor zu geben, aktivierst du das Plugin, das ihn bereitstellt, und schaltest den Sensor ein, alles in den Einstellungen der Kamera. Jeder Sensor im System, auch die ohne Kamera, wird danach auf der <strong>Sensoren</strong>-Seite verwaltet. Beides erfordert Admin-Rechte.</p><h2 id="den-plugins-tab-offnen" tabindex="-1">Den Plugins-Tab öffnen <a class="header-anchor" href="#den-plugins-tab-offnen" aria-label="Permalink to &quot;Den Plugins-Tab öffnen&quot;">​</a></h2><p>Öffne die <a href="/de/cameras/settings">Einstellungen</a> einer Kamera und gehe zum <strong>Plugins</strong>-Tab. Er ist in Kategorien gegliedert:</p><ul><li><strong>Detection.</strong> Die Detektoren: Bewegung, Objekt, Audio, Gesicht und Kennzeichen.</li><li><strong>Accessories.</strong> Steuerbares Zubehör und Zustandssensoren, etwa Lichter, Schlösser, Schalter, Sirenen und Kontaktsensoren.</li><li><strong>Core.</strong> Single-Provider-Sensoren wie PTZ und Batterie.</li><li><strong>Hub.</strong> Smart-Home- und Plattform-Integrationen, etwa eine HomeKit-Bridge.</li><li><strong>More.</strong> Ganze Plugins für diese Kamera aktivieren oder deaktivieren.</li></ul><p>Eine Kamera, die über ein Plugin hinzugefügt wurde (etwa ONVIF oder eine Cloud-Kamera), hat zusätzlich eine Kategorie für dieses Plugin mit dessen Einstellungen.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/sensors/plugins-tab.png",
    alt: "Plugins-Tab der Kamera-Einstellungen"
  }, null, _parent));
  _push(`<h2 id="sensoren-zuweisen-und-aktivieren" tabindex="-1">Sensoren zuweisen und aktivieren <a class="header-anchor" href="#sensoren-zuweisen-und-aktivieren" aria-label="Permalink to &quot;Sensoren zuweisen und aktivieren&quot;">​</a></h2><p>Wähle innerhalb einer Kategorie einen <strong>Sensor-Typ</strong> und dann das <strong>Plugin</strong>, das ihn bereitstellen soll. Detection-Typen nehmen jeweils einen Anbieter; Zubehör kann von mehreren Plugins kommen. Jeder aktivierte Sensor erscheint in der <strong>Sensors</strong>-Liste, wo du ihn umbenennen kannst.</p><h2 id="einstellungen-konfigurieren" tabindex="-1">Einstellungen konfigurieren <a class="header-anchor" href="#einstellungen-konfigurieren" aria-label="Permalink to &quot;Einstellungen konfigurieren&quot;">​</a></h2><p>Viele Plugins und Sensoren haben eigene Optionen, die direkt als Formular erscheinen: Plugin-Einstellungen, die für diese Kamera gelten, und Einstellungen pro Sensor. Änderungen wirken sofort.</p><p>Einmal aktiviert, erscheinen Sensoren in der Übersicht der Kamera und auf dem Video. Siehe <a href="/de/sensors/controls">Steuerung &amp; Status</a>, um sie zu nutzen, und <a href="/de/sensors/ptz">PTZ &amp; Autotrack</a> für PTZ-Kameras.</p><h2 id="die-sensoren-seite" tabindex="-1">Die Sensoren-Seite <a class="header-anchor" href="#die-sensoren-seite" aria-label="Permalink to &quot;Die Sensoren-Seite&quot;">​</a></h2><p>Die <strong>Sensoren</strong>-Seite listet jeden Sensor im System: von Plugins bereitgestellte, Kamera-Hardware und virtuelle. Jede Zeile zeigt Verbindungsstatus, Name, Typ, lieferndes Plugin und zugewiesene Kameras. Kamera-Hardware trägt ein Schloss neben ihrer Kamera; ein Sensor, der fürs Smart Home ausgeblendet ist, ein durchgestrichenes Auge neben dem Namen. Suche und sortierbare Spalten halten große Setups überschaubar.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/sensors/sensors-page.png",
    alt: "Sensoren-Seite mit allen Sensoren"
  }, null, _parent));
  _push(`<p>Klicke auf eine Zeile, um den Sensor zu bearbeiten:</p><ul><li><strong>Name.</strong> Wie der Sensor überall erscheint.</li><li><strong>Zugewiesene Kameras.</strong> Wähle beliebig viele Kameras. Der Sensor erscheint bei diesen Kameras und kann deren Erkennung auslösen. Kamera-Hardware ist fest an ihre Kamera gebunden und lässt sich nicht umziehen.</li><li><strong>Sensor freigeben.</strong> Ob der Sensor in HomeKit, Home Assistant und MQTT erscheint.</li></ul><p>Steuerbare Sensoren lassen sich direkt in diesem Dialog bedienen.</p><p>Jede Zeile bietet ein paar Aktionen:</p><ul><li><strong>Verlauf.</strong> Die aufgezeichneten Zustandsänderungen des Sensors.</li><li><strong>Sensor ausblenden.</strong> Nimmt die Zeile aus der Liste, für Sensoren, die dich nicht interessieren. <strong>Ausgeblendete anzeigen</strong> unten holt sie zurück; am Sensor selbst ändert das nichts.</li><li><strong>Sensor löschen.</strong> Nur virtuelle Sensoren und getrennte Plugin-Überbleibsel lassen sich löschen. Ein Sensor, dessen Plugin verbunden ist, käme beim nächsten Verbinden ohnehin zurück, deshalb ist der Button dort deaktiviert.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></li></ul><h2 id="virtuelle-sensoren" tabindex="-1">Virtuelle Sensoren <a class="header-anchor" href="#virtuelle-sensoren" aria-label="Permalink to &quot;Virtuelle Sensoren&quot;">​</a></h2><p>Hinter manchen Sensoren steckt kein Plugin: die erstellst du selbst auf der <strong>Sensoren</strong>-Seite. Siehe <a href="/de/sensors/virtual">Virtuelle Sensoren</a>.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Löschen entfernt den Sensor und seine Zuweisungen. Ein gelöschter Plugin-Sensor wird als neuer Sensor angelegt, wenn sein Plugin ihn erneut registriert, und alles, was auf den alten verwies (Automationen, Smart-Home-Freigaben), muss auf den neuen zeigen. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("de/sensors/setup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const setup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  setup as default
};
