import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Dashboard Cards","description":"","frontmatter":{"title":"Dashboard Cards"},"headers":[],"relativePath":"home-assistant/card.md","filePath":"home-assistant/card.md","lastUpdated":1784589260000}');
const _sfc_main = { name: "home-assistant/card.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /home-assistant/card.md for this page in Markdown format</div><h1 id="dashboard-cards" tabindex="-1">Dashboard Cards <a class="header-anchor" href="#dashboard-cards" aria-label="Permalink to &quot;Dashboard Cards&quot;">​</a></h1><p>The camera.ui integration ships two custom Lovelace cards for your Home Assistant dashboards:</p><ul><li><strong>camera.ui Card.</strong> A single-camera live view.</li><li><strong>camera.ui Grid.</strong> A grid of live tiles, click any tile to go live.</li></ul><p>Both cards stream through Home Assistant, show a snapshot poster until you go live, and expose resolution, transport and PTZ controls for cameras that support them.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/home-assistant/card.png",
    alt: "camera.ui single-camera card with a live stream and player controls"
  }, null, _parent));
  _push(`<h2 id="before-you-start" tabindex="-1">Before you start <a class="header-anchor" href="#before-you-start" aria-label="Permalink to &quot;Before you start&quot;">​</a></h2><p>Set up the <a href="/home-assistant/integration">camera.ui integration</a> first. When the integration loads, it serves the card bundle and registers it as a Lovelace resource for you. There is no manual resource step: the cards are available in the card picker as soon as the integration is running.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><h2 id="add-a-card" tabindex="-1">Add a card <a class="header-anchor" href="#add-a-card" aria-label="Permalink to &quot;Add a card&quot;">​</a></h2><ol><li>Open a dashboard and choose <strong>Edit dashboard</strong>, then <strong>Add card</strong>.</li><li>In the card picker, search for <strong>camera.ui Card</strong> or <strong>camera.ui Grid</strong>.</li><li>Pick the card, set the entity (or the camera list for the grid), and save.</li></ol><p>You can also add a card in YAML mode. The card <code>type:</code> values are <code>cameraui-card</code> and <code>cameraui-grid-card</code>.</p><p>The single card checks its entity and shows an inline message instead of a stream when something is off: <strong>No entity configured</strong>, <strong>Entity not found</strong>, or <strong>Not a camera.ui camera entity</strong> if the entity isn&#39;t a camera.ui camera. The grid card skips any entity it can&#39;t resolve and shows <strong>No cameras configured</strong> when none are left.</p><h2 id="camera-ui-card" tabindex="-1">camera.ui Card <a class="header-anchor" href="#camera-ui-card" aria-label="Permalink to &quot;camera.ui Card&quot;">​</a></h2><p>The single-camera card. <code>entity</code> is required.</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">cameraui-card</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">entity</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.front_door</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">title</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">Front Door</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">source</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">high-resolution</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">auto</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">autostart</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">snapshot_interval</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">10</span></span></code></pre></div><p>Options:</p><ul><li><strong>entity.</strong> Required. The camera.ui camera entity to show.</li><li><strong>title.</strong> Overlay title. Defaults to the entity&#39;s friendly name or camera name.</li><li><strong>source.</strong> Which resolution role to start on: <code>high-resolution</code>, <code>mid-resolution</code> or <code>low-resolution</code>. Defaults to <code>high-resolution</code>.</li><li><strong>mode.</strong> Streaming transport: <code>auto</code>, <code>webrtc</code> or <code>mse</code>. Defaults to <code>auto</code>, which picks WebRTC or MSE for you.</li><li><strong>autostart.</strong> Go live immediately instead of showing the poster first. Defaults to <code>false</code>.</li><li><strong>snapshot_interval.</strong> How often the snapshot poster refreshes, in seconds. Defaults to <code>10</code>, minimum <code>2</code>.</li></ul><h2 id="camera-ui-grid" tabindex="-1">camera.ui Grid <a class="header-anchor" href="#camera-ui-grid" aria-label="Permalink to &quot;camera.ui Grid&quot;">​</a></h2><p>The grid card shows several cameras as live tiles. <code>cameras</code> is required.</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">cameraui-grid-card</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">cameras</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.front_door</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.driveway</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">camera.garden</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">columns</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">3</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">source</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">high-resolution</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">mode</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">auto</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">autostart</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">false</span></span></code></pre></div><p>Options:</p><ul><li><strong>cameras.</strong> Required. A list of camera.ui camera entity ids.</li><li><strong>columns.</strong> Number of columns. When you leave it out, the grid uses 1 column for a single camera, 2 for up to four, and 3 above that.</li><li><strong>source, mode, autostart.</strong> Same meaning as on the single card, applied to every tile.</li></ul><h2 id="streaming" tabindex="-1">Streaming <a class="header-anchor" href="#streaming" aria-label="Permalink to &quot;Streaming&quot;">​</a></h2><p>The card shows a snapshot poster until you go live. A small badge in the bottom-left corner shows how old the snapshot is (<code>now</code>, seconds, minutes or hours). Click the play button, or set <code>autostart: true</code>, to open the live stream.</p><p>The live stream runs through the streaming engine over WebRTC or MSE, proxied through Home Assistant so nothing needs to be exposed directly. With <code>mode: auto</code> the card picks the transport; the mode pill lets you cycle <strong>AUTO → WebRTC → MSE</strong> while watching. H.265 cameras are supported too.<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup></p><p>When a camera has more than one resolution role, a resolution pill switches between <strong>HD</strong>, <strong>MD</strong> and <strong>SD</strong>. Controls appear on hover: pause and play, mute, picture-in-picture, and fullscreen. Narrow cards hide the extra controls to keep the video clear.<sup class="footnote-ref"><a href="#fn3" id="fnref3">[3]</a></sup></p><h2 id="ptz-controls" tabindex="-1">PTZ controls <a class="header-anchor" href="#ptz-controls" aria-label="Permalink to &quot;PTZ controls&quot;">​</a></h2><p>Cameras that expose PTZ get an on-video overlay when the card is wide enough: a zoom slider on the left and a pan/tilt pad on the right. Holding a control sends a continuous move; releasing stops it. If the camera has a home preset, tapping the pad sends it home. The overlay only shows the controls the camera actually supports.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/home-assistant/card-ptz.png",
    alt: "camera.ui card with the PTZ overlay showing a zoom slider and a pan and tilt pad"
  }, null, _parent));
  _push(`<p>Under the hood the overlay calls the <code>cameraui.ptz</code> service, so you can drive the same camera from your own automations.</p><h2 id="what-the-cards-do-not-do" tabindex="-1">What the cards do not do <a class="header-anchor" href="#what-the-cards-do-not-do" aria-label="Permalink to &quot;What the cards do not do&quot;">​</a></h2><p>The cards are live view only. They do not draw detection boxes or object-sensor badges, and there is no recordings or events timeline inside the card. For object sensors, device triggers and the <code>cameraui_event</code> bus event, see the <a href="/home-assistant/integration">integration page</a>.</p><h2 id="next-steps" tabindex="-1">Next steps <a class="header-anchor" href="#next-steps" aria-label="Permalink to &quot;Next steps&quot;">​</a></h2><ul><li><strong><a href="/home-assistant/integration">Home Assistant integration</a></strong> — set up the integration, object sensors and automations.</li></ul><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>In storage-mode dashboards the integration creates or updates the Lovelace resource with a content-hashed URL. In YAML-mode dashboards it injects the script for the session instead. Either way, you do not add a resource by hand. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li><li id="fn2" class="footnote-item"><p>The stream backend is go2rtc, proxied through Home Assistant. Codec handling, including H.265, lives in the shared streaming component the card embeds. <a href="#fnref2" class="footnote-backref">↩︎</a></p></li><li id="fn3" class="footnote-item"><p>The pills hide below 300px card width, picture-in-picture below 260px, mute below 200px, and the PTZ overlay needs at least 340px. <a href="#fnref3" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("home-assistant/card.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const card = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  card as default
};
