import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Desktop app","description":"","frontmatter":{},"headers":[],"relativePath":"install/desktop.md","filePath":"install/desktop.md","lastUpdated":1784139260000}');
const _sfc_main = { name: "install/desktop.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /install/desktop.md for this page in Markdown format</div><h1 id="desktop-app" tabindex="-1">Desktop app <a class="header-anchor" href="#desktop-app" aria-label="Permalink to &quot;Desktop app&quot;">​</a></h1><p>The desktop app is the recommended way to run camera.ui on <strong>macOS and Windows</strong>. One download installs the server and the viewer together, so you have a working setup in a couple of clicks. It also runs on Linux, though there a <a href="/install/docker">Docker</a> or <a href="/install/proxmox">Proxmox</a> server is the better choice (see <a href="/install/">Which installation?</a>).</p><h2 id="download" tabindex="-1">Download <a class="header-anchor" href="#download" aria-label="Permalink to &quot;Download&quot;">​</a></h2><p>Download the installer for your platform, directly below or from the <a href="https://cameraui.com/#download" target="_blank" rel="noreferrer">download page</a>. The links always point to the latest release.</p><table tabindex="0"><thead><tr><th>Platform</th><th>Download</th></tr></thead><tbody><tr><td>macOS (Apple Silicon)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-arm64.dmg" target="_blank" rel="noreferrer"><code>camera.ui-arm64.dmg</code></a></td></tr><tr><td>macOS (Intel)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x64.dmg" target="_blank" rel="noreferrer"><code>camera.ui-x64.dmg</code></a></td></tr><tr><td>Windows 10 / 11</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x64.exe" target="_blank" rel="noreferrer"><code>camera.ui-x64.exe</code></a></td></tr><tr><td>Linux (AppImage)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-x86_64.AppImage" target="_blank" rel="noreferrer"><code>x64</code></a> · <a href="https://downloads.cameraui.com/latest/camera.ui-arm64.AppImage" target="_blank" rel="noreferrer"><code>arm64</code></a></td></tr><tr><td>Linux (.deb)</td><td><a href="https://downloads.cameraui.com/latest/camera.ui-amd64.deb" target="_blank" rel="noreferrer"><code>amd64</code></a> · <a href="https://downloads.cameraui.com/latest/camera.ui-arm64.deb" target="_blank" rel="noreferrer"><code>arm64</code></a></td></tr></tbody></table><p>Apple Silicon and Intel Macs use separate downloads. Pick the one that matches your Mac.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-download.png",
    alt: "camera.ui download page"
  }, null, _parent));
  _push(`<h2 id="install" tabindex="-1">Install <a class="header-anchor" href="#install" aria-label="Permalink to &quot;Install&quot;">​</a></h2><h3 id="macos" tabindex="-1">macOS <a class="header-anchor" href="#macos" aria-label="Permalink to &quot;macOS&quot;">​</a></h3><p>Open the downloaded <code>.dmg</code> and drag <strong>camera.ui</strong> into your Applications folder, then launch it from there. The app is signed and notarized by Apple, so it opens without extra warnings.</p><h3 id="windows" tabindex="-1">Windows <a class="header-anchor" href="#windows" aria-label="Permalink to &quot;Windows&quot;">​</a></h3><p>Run the downloaded <code>.exe</code>. The installer lets you choose where to install and sets up the app for the current user, so no administrator rights are needed.</p><p>Windows may show a <strong>SmartScreen</strong> warning, because the app is not code-signed yet. Select <strong>More info → Run anyway</strong> to continue.</p><h3 id="linux" tabindex="-1">Linux <a class="header-anchor" href="#linux" aria-label="Permalink to &quot;Linux&quot;">​</a></h3><p>Install the <code>.deb</code> with your package manager:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">sudo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> apt</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ./camera.ui-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">.deb</span></span></code></pre></div><p>Or make the <code>.AppImage</code> executable and run it:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">chmod</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> +x</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> camera.ui-</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">*</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">.AppImage</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">./camera.ui-*.AppImage</span></span></code></pre></div><div class="tip custom-block"><p class="custom-block-title">Pick the <code>.AppImage</code> if you want automatic updates</p><p>Only the <code>.AppImage</code> updates itself. A <code>.deb</code> install stays on its version. Update it by downloading and installing the new <code>.deb</code>.</p></div><h2 id="first-launch-choose-how-to-run" tabindex="-1">First launch: choose how to run <a class="header-anchor" href="#first-launch-choose-how-to-run" aria-label="Permalink to &quot;First launch: choose how to run&quot;">​</a></h2><p>The first time you open the app, it asks <strong>&quot;How should camera.ui run?&quot;</strong> and offers four modes:</p><ul><li><strong>Server.</strong> Runs the camera.ui server on this machine. This is the all-in-one option, and what most people on macOS and Windows pick.</li><li><strong>Worker.</strong> Takes on part of the work for another camera.ui server on your network. Enter the address of the main server and a pairing code from its <strong>Workers</strong> settings. See <a href="/admin/workers#worker-with-the-desktop-app">Workers</a>.</li><li><strong>Viewer · Direct.</strong> Connects to an existing server by address, for example another machine on your network.</li><li><strong>Viewer · Cloud.</strong> Signs in via cloud.cameraui.com to reach a server through <a href="/remote/cloud">camera.ui Cloud</a>.</li></ul>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-mode-picker.png",
    alt: "Desktop first-launch mode picker"
  }, null, _parent));
  _push(`<p>In <strong>Server</strong> mode the app starts the server, opens the interface, and guides you through <a href="/intro/getting-started">first-run setup</a>. In a <strong>Viewer</strong> mode it connects to a server you already have. In <strong>Worker</strong> mode there is no window, only the tray icon and a status screen.</p><h2 id="the-tray-icon" tabindex="-1">The tray icon <a class="header-anchor" href="#the-tray-icon" aria-label="Permalink to &quot;The tray icon&quot;">​</a></h2><p>The tray icon holds the app&#39;s own settings:</p><ul><li><strong>Open.</strong> Brings the window back.</li><li><strong>Open At Login.</strong> Starts camera.ui when you log in. It goes straight to the tray: no window, no splash. Open it from the tray icon when you need it.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></li><li><strong>Close to tray.</strong> Off by default. Turn it on and closing the window only hides it, so a server on this machine keeps running.<sup class="footnote-ref"><a href="#fn2" id="fnref2">[2]</a></sup></li><li><strong>Switch mode….</strong> Changes how the app runs, without reinstalling.</li><li><strong>Quit.</strong> Stops the app, and in Server mode the server with it.</li></ul><p>On Windows, left-click the tray icon to open the window, right-click for the menu.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/install/desktop-tray-menu.png",
    alt: "Desktop tray menu"
  }, null, _parent));
  _push(`<h2 id="macos-permissions" tabindex="-1">macOS permissions <a class="header-anchor" href="#macos-permissions" aria-label="Permalink to &quot;macOS permissions&quot;">​</a></h2><p>On macOS 15 and newer, the system asks for <strong>local network</strong> access on first launch. Allow it, otherwise the app can&#39;t reach cameras on your network. The first time you use two-way talk, macOS also asks for <strong>microphone</strong> access, and the first time you use the geofence trigger&#39;s &quot;My location&quot; button in <a href="/automations/">Automations</a>, it asks for <strong>location</strong> access.</p><h2 id="updates" tabindex="-1">Updates <a class="header-anchor" href="#updates" aria-label="Permalink to &quot;Updates&quot;">​</a></h2><p>The desktop app keeps itself up to date. It checks for updates when it starts and periodically while running, then downloads and installs them for you. In Server mode it also updates the bundled server before starting it, so the app and the server stay in sync.</p><p>One exception on Linux: only the <code>.AppImage</code> updates itself. If you installed the <code>.deb</code>, update by downloading and installing the new <code>.deb</code> from the <a href="https://cameraui.com" target="_blank" rel="noreferrer">download page</a>.</p><h2 id="where-your-data-lives" tabindex="-1">Where your data lives <a class="header-anchor" href="#where-your-data-lives" aria-label="Permalink to &quot;Where your data lives&quot;">​</a></h2><p>In Server mode, your settings and recordings are stored in a <code>camera.ui/volume</code> folder inside the app&#39;s per-user data directory:</p><ul><li><strong>macOS:</strong> <code>~/Library/Application Support/camera.ui/camera.ui/volume</code></li><li><strong>Windows:</strong> <code>%APPDATA%\\camera.ui\\camera.ui\\volume</code></li><li><strong>Linux:</strong> <code>~/.config/camera.ui/camera.ui/volume</code></li></ul><p>See <a href="/admin/backup">Backup &amp; restore</a> to keep a copy.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>macOS and Windows only. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li><li id="fn2" class="footnote-item"><p>Windows and Linux only. On macOS the app stays in the tray when you close the window anyway, so the option isn&#39;t there. <a href="#fnref2" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("install/desktop.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const desktop = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  desktop as default
};
