import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Plugins","description":"","frontmatter":{"title":"Plugins"},"headers":[],"relativePath":"plugins/index.md","filePath":"plugins/index.md","lastUpdated":1784589260000}');
const _sfc_main = { name: "plugins/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /plugins.md for this page in Markdown format</div><h1 id="plugins" tabindex="-1">Plugins <a class="header-anchor" href="#plugins" aria-label="Permalink to &quot;Plugins&quot;">​</a></h1><p>Plugins extend camera.ui. Most of what it does beyond live view comes from plugins you install: the <a href="/detection/">AI backends and motion engines</a> that power detection, audio detection, smart-home bridges like <a href="/plugins/homekit">HomeKit</a>, and integrations for various camera brands. Managing plugins is an admin task.</p><h2 id="two-things-kept-separate" tabindex="-1">Two things, kept separate <a class="header-anchor" href="#two-things-kept-separate" aria-label="Permalink to &quot;Two things, kept separate&quot;">​</a></h2><ul><li><strong>Installing a plugin</strong> adds it to your server, once. That&#39;s what this section covers.</li><li><strong>Assigning a plugin</strong> to a camera decides which camera uses it, for example which motion engine a camera runs. That&#39;s done per camera, in <a href="/sensors/setup">Set up sensors</a>.</li></ul><h2 id="managing-plugins" tabindex="-1">Managing plugins <a class="header-anchor" href="#managing-plugins" aria-label="Permalink to &quot;Managing plugins&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/plugins/plugins-list.png",
    alt: "The Plugins page"
  }, null, _parent));
  _push(`<p>Open <strong>Plugins</strong> from the menu to see everything installed, each as a card with a live status (ready, started, stopped, error). From a card you can:</p><ul><li><strong>Enable or disable</strong> it, and <strong>start, stop, or restart</strong> its process.</li><li><strong>Update</strong> it when a new version is available, or pick a <strong>specific version</strong>.</li><li><strong>Open its settings</strong>, or view its <strong>logs</strong> if something&#39;s wrong.</li><li><strong>Uninstall</strong> it, optionally removing its stored data.</li></ul><p>Recordings are the exception: if you delete a recording plugin&#39;s stored data, its footage is kept.</p><p>The gear button next to the search bar holds two settings, both off by default:</p><ul><li><strong>Beta versions.</strong> Shows pre-release versions in the version picker and offers beta releases as updates.</li><li><strong>Allow plugin build scripts.</strong> Lets plugins run install scripts and native builds while installing or updating. Only turn this on for plugins you trust.</li></ul><p>Plugins run as their own process, so one misbehaving plugin won&#39;t take down the rest. They can be written in Node, Python, or Go; a small badge on each card shows which.</p><h2 id="installing-a-plugin" tabindex="-1">Installing a plugin <a class="header-anchor" href="#installing-a-plugin" aria-label="Permalink to &quot;Installing a plugin&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/plugins/plugin-store.png",
    alt: "The plugin store"
  }, null, _parent));
  _push(`<p>Choose <strong>Search plugins</strong> to open the store. The list comes from npm, so any package published as a camera.ui plugin can appear and it isn&#39;t a fixed catalog, but camera.ui curates what you see on top of it:</p><ul><li><strong>Trust.</strong> Each plugin is marked <strong>Official</strong> (published by camera.ui), <strong>Verified</strong> (a community plugin the camera.ui team has reviewed), or <strong>Community</strong> (published by anyone, not reviewed). You can filter by trust level.</li><li><strong>Safety.</strong> Plugins known to be malicious or compromised are blocked: they don&#39;t show up, can&#39;t be installed, and one you already have is disabled automatically if it&#39;s later blocked.</li><li><strong>Browsing.</strong> Filter by category, start from the featured plugins, and sort by name, weekly downloads, or last update. Each entry shows its logo, a short description, and its download numbers.</li></ul><p>Pick a plugin and install it, choosing a specific version if you like. Once installed, enable it and assign it where it&#39;s needed.</p><h2 id="settings" tabindex="-1">Settings <a class="header-anchor" href="#settings" aria-label="Permalink to &quot;Settings&quot;">​</a></h2><p>A plugin&#39;s own settings live on its page, under <strong>Settings</strong>, and apply server-wide. Settings that affect a single camera are edited in that <a href="/cameras/settings">camera&#39;s settings</a> instead. Recording-plugin settings are kept with the rest of <a href="/recording/">recording</a>.</p><h2 id="setup-guides" tabindex="-1">Setup guides <a class="header-anchor" href="#setup-guides" aria-label="Permalink to &quot;Setup guides&quot;">​</a></h2><ul><li><strong><a href="/plugins/homekit">HomeKit</a></strong> — add your cameras to Apple Home.</li><li><strong><a href="/home-assistant/">Home Assistant</a></strong> — cameras, sensors and detection events as Home Assistant entities.</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("plugins/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
