import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Recording (NVR)","description":"","frontmatter":{"title":"Recording (NVR)"},"headers":[],"relativePath":"recording/index.md","filePath":"recording/index.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "recording/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /recording.md for this page in Markdown format</div><h1 id="recording-nvr" tabindex="-1">Recording (NVR) <a class="header-anchor" href="#recording-nvr" aria-label="Permalink to &quot;Recording (NVR)&quot;">​</a></h1><p>camera.ui records your cameras so you can go back and watch what happened. Recording and everything in this section need an active camera.ui subscription.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p><div class="info custom-block"><p class="custom-block-title">Trying recording during the beta</p><p>Subscriptions aren&#39;t open for purchase yet. To test recording, create your camera.ui account at <a href="https://cloud.cameraui.com/" target="_blank" rel="noreferrer">cloud.cameraui.com</a>, then ask for a trial on our <a href="https://discord.gg/bBGnGcbz8N" target="_blank" rel="noreferrer">Discord</a>.</p></div><h2 id="turning-on-recording" tabindex="-1">Turning on recording <a class="header-anchor" href="#turning-on-recording" aria-label="Permalink to &quot;Turning on recording&quot;">​</a></h2><p>Recording comes from the <strong>camera.ui NVR</strong> plugin, which is installed by default, and runs on a subscription tied to your camera.ui account. To turn it on:</p><ol><li>In <strong>Settings → Remote Access</strong>, choose <strong>Register server</strong> and sign in with your camera.ui account. This links the server to your account; you don&#39;t need to enable remote cloud access for it.</li><li>Open <strong>Settings → Recordings</strong> and, in the <strong>License &amp; Cloud</strong> card, click the <strong>cloud icon</strong> and sign in. It&#39;s grey when you&#39;re not connected and turns green once you are.</li><li>Your license then activates automatically. If the status doesn&#39;t update, use the <strong>Refetch License</strong> button.</li></ol><p>Once the license is active, cameras you add start recording on their own, as long as your subscription still has a free camera slot. A new camera records continuously in every stream quality. You can change the mode, pick which qualities to record, or turn recording off in the camera&#39;s recording settings.</p><h2 id="recording-modes" tabindex="-1">Recording modes <a class="header-anchor" href="#recording-modes" aria-label="Permalink to &quot;Recording modes&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/recording/recording-modes.png",
    alt: "Recording mode settings"
  }, null, _parent));
  _push(`<p>Each camera records in one of three modes, set in its recording settings:</p><ul><li><strong>Continuous.</strong> Records around the clock. You always have footage, at the cost of the most storage.</li><li><strong>Event.</strong> Records only when something happens (motion, an object, a sensor). A <strong>pre-buffer</strong> keeps a few seconds before each trigger, so you don&#39;t miss the lead-up.</li><li><strong>Ad-hoc.</strong> Connects to the camera only when an event fires. Useful for cameras that stop sending events while a stream is open, such as some battery cameras.</li></ul><h2 id="quality" tabindex="-1">Quality <a class="header-anchor" href="#quality" aria-label="Permalink to &quot;Quality&quot;">​</a></h2><p>You choose which stream qualities to record, <strong>high</strong>, <strong>mid</strong>, or <strong>low</strong>, and can keep more than one. Recording a low-resolution stream as well makes scrubbing the <a href="/recording/timeline-playback">timeline</a> fast and smooth.</p><h2 id="next" tabindex="-1">Next <a class="header-anchor" href="#next" aria-label="Permalink to &quot;Next&quot;">​</a></h2><ul><li><strong><a href="/recording/storage">Storage &amp; retention</a></strong> — where recordings live and how long they&#39;re kept.</li><li><strong><a href="/recording/timeline-playback">Timeline &amp; playback</a></strong> — review footage.</li><li><strong><a href="/recording/export">Export &amp; download</a></strong> — save a clip.</li><li><strong><a href="/recording/browsing">Browsing &amp; filters</a></strong> — find past events.</li></ul><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Recording (NVR) requires an active camera.ui subscription. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("recording/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
