import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"camera.ui Cloud","description":"","frontmatter":{"title":"camera.ui Cloud"},"headers":[],"relativePath":"remote/cloud.md","filePath":"remote/cloud.md","lastUpdated":1784134587000}');
const _sfc_main = { name: "remote/cloud.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /remote/cloud.md for this page in Markdown format</div><h1 id="camera-ui-cloud" tabindex="-1">camera.ui Cloud <a class="header-anchor" href="#camera-ui-cloud" aria-label="Permalink to &quot;camera.ui Cloud&quot;">​</a></h1><p>camera.ui Cloud lets you reach your server from anywhere without touching your router. Your server registers with the cloud, and you connect through your camera.ui account. It&#39;s free and separate from the recording subscription.</p><h2 id="your-server-stays-yours" tabindex="-1">Your server stays yours <a class="header-anchor" href="#your-server-stays-yours" aria-label="Permalink to &quot;Your server stays yours&quot;">​</a></h2><p>camera.ui Cloud is a way to reach your own server, not a copy of it. Your cameras, recordings, settings, and the interface all stay on your server. The cloud&#39;s only job is to help your app and your server connect, and your session then runs directly to your own instance. Your video, credentials, and other data go straight to your server and are never visible to camera.ui.</p><h2 id="enabling-it" tabindex="-1">Enabling it <a class="header-anchor" href="#enabling-it" aria-label="Permalink to &quot;Enabling it&quot;">​</a></h2>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/remote/remote-settings.png",
    alt: "The Cloud card in Settings, Remote"
  }, null, _parent));
  _push(`<p>In <strong>Settings → Remote</strong>, open the <strong>Cloud</strong> card and turn on <strong>Enabled</strong>. Give the server a <strong>name</strong>; this is how it appears in your cloud dashboard, which helps once you have more than one.</p><p>The <strong>status</strong> row shows whether the server is <strong>Registered</strong>, and a <strong>tunnel</strong> indicator shows the live connection. To connect a server, choose <strong>Register server</strong> and complete the pairing. If the status shows <strong>Re-authentication required</strong>, the server lost its cloud credentials: choose <strong>Reconnect</strong> and pair again. A registered server can be taken off your account with <strong>Unregister server</strong>. The same flow on a phone is covered in <a href="/remote/pairing">Pairing mobile apps</a>.</p><h2 id="cloud-keeps-direct-access-on" tabindex="-1">Cloud keeps direct access on <a class="header-anchor" href="#cloud-keeps-direct-access-on" aria-label="Permalink to &quot;Cloud keeps direct access on&quot;">​</a></h2><p>While Cloud is on, your server also keeps a public address so the apps can reach it. That&#39;s why the <strong>Enabled</strong> switch in the <strong>Direct connection</strong> card is locked on, and the <strong>External URL</strong> row shows the address in use.</p><p>If you haven&#39;t set up a direct address, or the one you configured can&#39;t be reached, camera.ui starts a temporary Cloudflare tunnel instead. Either way you don&#39;t have to touch your router. If you&#39;d rather use your own address, set it up under <a href="/remote/">Direct connection</a>.</p><h2 id="the-cloud-dashboard" tabindex="-1">The cloud dashboard <a class="header-anchor" href="#the-cloud-dashboard" aria-label="Permalink to &quot;The cloud dashboard&quot;">​</a></h2><p>Signing in to your camera.ui account gives you a dashboard listing all your registered servers by name. From there you pick a server to connect to. You can also <strong>share a server</strong> with another camera.ui account by invite, so family members can access it with their own login.</p><h2 id="turning-it-off" tabindex="-1">Turning it off <a class="header-anchor" href="#turning-it-off" aria-label="Permalink to &quot;Turning it off&quot;">​</a></h2><p>Disabling cloud access ends any active remote sessions. Local connections on your network keep working.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("remote/cloud.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const cloud = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  cloud as default
};
