import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Set up sensors","description":"","frontmatter":{"title":"Set up sensors"},"headers":[],"relativePath":"sensors/setup.md","filePath":"sensors/setup.md","lastUpdated":1785427198000}');
const _sfc_main = { name: "sensors/setup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_Shot = resolveComponent("Shot");
  _push(`<div${ssrRenderAttrs(_attrs)}><div style="${ssrRenderStyle({ "display": "none" })}" hidden="true" aria-hidden="true" data-nosnippet>Are you an LLM? You can read better optimized documentation at /sensors/setup.md for this page in Markdown format</div><h1 id="set-up-sensors" tabindex="-1">Set up sensors <a class="header-anchor" href="#set-up-sensors" aria-label="Permalink to &quot;Set up sensors&quot;">​</a></h1><p>Most sensors come from <a href="/plugins/">plugins</a>. To give a camera a sensor, you enable the plugin that provides it and turn the sensor on, all from the camera&#39;s settings. Every sensor in the system, including ones that belong to no camera, is then managed on the <strong>Sensors</strong> page. Both need admin.</p><h2 id="open-the-plugins-tab" tabindex="-1">Open the Plugins tab <a class="header-anchor" href="#open-the-plugins-tab" aria-label="Permalink to &quot;Open the Plugins tab&quot;">​</a></h2><p>Open a camera&#39;s <a href="/cameras/settings">settings</a> and go to the <strong>Plugins</strong> tab. It is grouped into categories:</p><ul><li><strong>Detection.</strong> The detectors: motion, object, audio, face, and license plate.</li><li><strong>Accessories.</strong> Controllable accessories and state sensors, such as lights, locks, switches, sirens, and contact sensors.</li><li><strong>Core.</strong> Single-provider sensors such as PTZ and battery.</li><li><strong>Hub.</strong> Smart-home and platform integrations, such as a HomeKit bridge.</li><li><strong>More.</strong> Enable or disable whole plugins for this camera.</li></ul><p>A camera added through a plugin (such as ONVIF or a cloud camera) also has a category for that plugin, holding its settings.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/sensors/plugins-tab.png",
    alt: "Camera settings Plugins tab"
  }, null, _parent));
  _push(`<h2 id="assign-and-enable-sensors" tabindex="-1">Assign and enable sensors <a class="header-anchor" href="#assign-and-enable-sensors" aria-label="Permalink to &quot;Assign and enable sensors&quot;">​</a></h2><p>Within a category, pick a <strong>sensor type</strong>, then choose the <strong>plugin</strong> that should provide it. Detection types take one provider at a time; accessories can come from several plugins. Each enabled sensor appears in the <strong>Sensors</strong> list, where you can rename it.</p><h2 id="configure-settings" tabindex="-1">Configure settings <a class="header-anchor" href="#configure-settings" aria-label="Permalink to &quot;Configure settings&quot;">​</a></h2><p>Many plugins and sensors have their own options, shown right there as a form: plugin settings that apply to this camera, and per-sensor settings. Changes take effect immediately.</p><p>Once enabled, sensors show up in the camera&#39;s Overview and on the video. See <a href="/sensors/controls">Controls &amp; states</a> to use them, and <a href="/sensors/ptz">PTZ &amp; autotrack</a> for PTZ cameras.</p><h2 id="the-sensors-page" tabindex="-1">The Sensors page <a class="header-anchor" href="#the-sensors-page" aria-label="Permalink to &quot;The Sensors page&quot;">​</a></h2><p>The <strong>Sensors</strong> page lists every sensor in the system: plugin-provided, camera hardware, and virtual. Each row shows the connection state, name, type, providing plugin, and assigned cameras. Camera hardware shows a lock next to its camera; a sensor that is hidden from your smart home carries a crossed-out eye next to its name. Search and the sortable columns keep large setups manageable.</p>`);
  _push(ssrRenderComponent(_component_Shot, {
    src: "/img/sensors/sensors-page.png",
    alt: "Sensors page listing all sensors"
  }, null, _parent));
  _push(`<p>Click a row to edit the sensor:</p><ul><li><strong>Name.</strong> How the sensor appears everywhere.</li><li><strong>Assigned cameras.</strong> Pick any number of cameras. The sensor shows up on those cameras and can trigger their detection. Camera hardware is fixed to its camera and can&#39;t be re-assigned.</li><li><strong>Expose sensor.</strong> Whether the sensor shows up in HomeKit, Home Assistant, and MQTT.</li></ul><p>Controllable sensors can also be operated right in this dialog.</p><p>Each row offers a few actions:</p><ul><li><strong>History.</strong> The sensor&#39;s recorded state changes.</li><li><strong>Hide sensor.</strong> Takes the row out of the list, for sensors you don&#39;t care about. <strong>Show hidden</strong> at the bottom brings them back; hiding changes nothing about the sensor itself.</li><li><strong>Delete sensor.</strong> Only virtual sensors and disconnected plugin leftovers can be deleted. A sensor whose plugin is connected would come back on the next reconnect anyway, so the button is disabled for those.<sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></li></ul><h2 id="virtual-sensors" tabindex="-1">Virtual sensors <a class="header-anchor" href="#virtual-sensors" aria-label="Permalink to &quot;Virtual sensors&quot;">​</a></h2><p>Some sensors have no plugin behind them: you create those yourself on the <strong>Sensors</strong> page. See <a href="/sensors/virtual">Virtual sensors</a>.</p><hr class="footnotes-sep"><section class="footnotes"><ol class="footnotes-list"><li id="fn1" class="footnote-item"><p>Deleting removes the sensor and its assignments. A deleted plugin sensor is recreated as a new sensor if its plugin registers it again, and anything that referenced the old one (automations, smart-home exports) must be pointed at the new sensor. <a href="#fnref1" class="footnote-backref">↩︎</a></p></li></ol></section></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("sensors/setup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const setup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  setup as default
};
